server:
  port: 8080


spring:
  profiles:
    # 本地开发环境 dev
    # 生产环境 prod
    active: prod
  devtools:
    restart:
      enabled: false
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB


  redis:
    # 单位：毫秒
    timeout: 5000
    # 如果使用的jedis 则将lettuce改成jedis即可
    jedis:
      pool:
        # 最大活跃链接数 默认8（使用负值表示没有限制）
        max-active: 10
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 5
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    lettuce:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 5
        max-wait: -1

  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 5
      maximum-pool-size: 20
      pool-name: bosPoolName
      max-lifetime: 1800000
      idle-timeout: 30000
      connection-timeout: 60000
      validation-timeout: 3000
      login-timeout: 5


# mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  # mapper xml地址
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  # 别名配置，实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.cc.api.src.pojo,com.cc.api.src.pojo.vo
  global-config:
    db-config:
      # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      # 字段验证策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
      # 驼峰下划线转换，表名和字段名是否使用下划线命名，默认false
      table-underline: true
      # 是否开启大写命名，默认不开启（开启后mybatisplus生成的sql中表名和id字段将变为大写）
      capital-mode: false
      # 全局逻辑删除的实体字段名(配置后可以忽略设置TableLogic注解)
      logic-delete-field: deleted
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，默认true
    map-underscore-to-camel-case: true
    # 返回map时，true:当查询数据为空时字段返回为null；false:不加这个查询数据为空时，字段将被隐藏
    #call-setters-on-nulls: true
    # sql日志打印 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启Mybatis二级缓存，默认为 true
    cache-enabled: true

pagehelper:
  # 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
  row-bounds-with-count: true
  helper-dialect: mysql


logging:
  config: classpath:logback-spring.xml